# Generated by Django 4.0 on 2021-12-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
    ]
