# Generated by Django 4.0 on 2021-12-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_order_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
