# Generated by Django 4.0 on 2021-12-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_date_added_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
    ]
